GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTc0NjE4NzAsIm1vYmlsZSI6IjE4ODgyMzA2MDAyIiwiaWQiOjE2OTY2NzgyMTYzNTIsImV4cCI6MTY5NzU0ODI3MCwiaWF0IjoxNjk3NDYxODcwfQ.h3Zk48bPs1ZMpo5NxEAQ-faOWzscRWnMiKNK25nXtHk
###


###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTc0MjY2MjUsIm1vYmlsZSI6IjE4ODgyMzA2MDAyIiwiaWQiOjE2OTY2NzgyMTYzNTIsImV4cCI6MTY5NzUxMzAyNSwiaWF0IjoxNjk3NDI2NjI1fQ.fukB40uxZq6XLV7aBhfno64LfmhAXoNSm6e2EcflQ0Y

{
  "name": "胡四",
  "idCard": "51446278",
  "type": "2"
}













###